from langchain_community.utilities import SQLDatabase
from langchain_google_genai import ChatGoogleGenerativeAI
import mysql.connector
from dotenv import load_dotenv

load_dotenv()

import mysql.connector
#if connection fails to the database
try:
    conn = mysql.connector.connect(
        host="localhost",
        user="root",
        password="root",
        database="college_erp_v2"
    )

    print("Database Connected!")

except mysql.connector.Error as e:

    print("Database Connection Failed")
    print(e)

    exit()

cursor = conn.cursor()


db = SQLDatabase.from_uri(
    "mysql+pymysql://root:root@localhost/college_erp_v2"
)
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash"
)
schema = db.get_table_info()
# print(schema)



    
question = input("Ask a question:").strip()




dangerous_words = [
    "delete",
    "drop",
    "update",
    "insert",
    "remove",
    "truncate",
    "alter",
    "modify"
]

if any(word in question.lower() for word in dangerous_words):
    print("Only SELECT queries are allowed.")
    exit()


cursor.execute("""
SELECT name
FROM students
GROUP BY name
HAVING COUNT(*) > 1
""")

duplicate_names = [row[0] for row in cursor.fetchall()]

# print(duplicate_names)

for name in duplicate_names:

    if name.lower() in question.lower():

        cursor.execute("""
        SELECT student_id,
               name,
               department
        FROM students
        WHERE name = %s
        """, (name,))

        students = cursor.fetchall()

        print(f"Multiple students named {name} found.Please provide student ID.")

        for student in students:
            print(student)

        exit()




prompt = f"""
You are an expert MySQL developer.

Database Schema:
{schema}

Your task is to convert the question into a SQL query.

Rules:
- Output ONLY SQL.
- No explanations.
- No markdown.
- No code fences.
- Only SELECT queries.
- Never generate INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, or CREATE statements.
- Use only tables and columns present in the schema.
- If the question cannot be answered using the schema, generate the closest valid SELECT query possible.

Question:
{question}
"""

#GEMINI QUOTA IF EXCEEDED
try:

    response = llm.invoke(prompt)

except Exception as e:

    if "429" in str(e):

        print(
            "Gemini quota exceeded. Try again later."
        )

    else:

        print("Gemini Error")
        print(e)

    exit()
print(response.content)


# running the sql query
sql_query = response.content

sql_query = sql_query.replace("```sql", "")
sql_query = sql_query.replace("```", "")
sql_query = sql_query.strip()


# ROLE-BASED AUTHORIZATION


# ALLOWS ONLY SELECT QUERIES
if not sql_query.upper().startswith("SELECT"):
    print("Only SELECT queries are allowed.")
else:
    try:
        #invalid sql query generated by LLM
        result = db.run(sql_query)
#if no table exists or result is empty
        if not result:
            print("No matching records found.")
        else:
# Handle NULL VALUES
            if "None" in str(result):
              print(
        "Some records contain missing values."
    )
            else:
                print(result)

    except Exception as e:
        print("Invalid SQL generated.")
        print(e)
   


summary_prompt = f"""
Question:
{question}
    
Result:
{result}

Answer naturally.
"""

answer = llm.invoke(summary_prompt)

print(answer.content)


